api_platform:
  title: La Grande Enfant API
  version: 1.0.0
  description: "API pour la boutique La Grande Enfant"
  formats:
    json: ["application/json"]
    jsonld: ["application/ld+json"]
  docs_formats:
    jsonld: ["application/ld+json"]
    jsonopenapi: ["application/vnd.openapi+json"]
    html: ["text/html"]
  defaults:
    pagination_items_per_page: 10
    stateless: true
    cache_headers:
      vary: ["Content-Type", "Authorization", "Origin"]
    extra_properties:
      standard_put: true
      rfc_7807_compliant_errors: true
  swagger:
    versions: [3]
    api_keys:
      JWT:
        name: Authorization
        type: header
