api_platform:
  title: La Grande Enfant API
  version: 1.0.0
  formats:
    json: ["application/json"]
  docs_formats:
    jsonld: ["application/ld+json"]
    jsonopenapi: ["application/vnd.openapi+json"]
    html: ["text/html"]
  defaults:
    pagination_items_per_page: 10 #30 Default value
    stateless: true
    cache_headers:
      vary: ["Content-Type", "Authorization", "Origin"]
    extra_properties:
      standard_put: true
      rfc_7807_compliant_errors: true
