version: "3"

services:
  ###> doctrine/doctrine-bundle ###
  database:
    image: mysql:latest
    container_name: mysql-la-grande-enfant
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: la-grande-enfant-db
    ports:
      - "6033:3306"
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin-la-grande-enfant:
    image: phpmyadmin:5.2
    container_name: phpmyadmin-la-grande-enfant
    links:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8080:80"

  ###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    ports: ["1025", "1080"]
  ###< symfony/mailer ###

volumes:
  dbdata:
